apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
  namespace: default
spec:
  hard:
    requests.cpu: "39.5"
    requests.memory: 153.5Gi
    limits.cpu: "66.1"
    limits.memory: 307Gi
---
