apiVersion : apps/v1
kind: Deployment
metadata:
  name: fromlogstocosmos
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fromlogstocosmos
  template:
    metadata:
      labels:
        app: fromlogstocosmos
        azure.workload.identity/use: "true"
    spec:
      os:
        name: linux
      serviceAccountName: "sa-workload-identity"
      nodeSelector:
        pool_type: User
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: pool_priority
                operator: In
                values:
                - Spot
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      containers:
      - name: fromlogstocosmos
        image: crmmglogs.azurecr.io/fromlogstocosmos
        env:
        - name: AZURE_KEYVAULT_URL
          valueFrom:
            configMapKeyRef:
              name: cm-logsm2c-fromlogstocosmos
              key: azure_keyvault_url
        - name: AZURE_SB_CONN_STR
          valueFrom:
            configMapKeyRef:
              name: cm-logsm2c-fromlogstocosmos
              key: azure_sb_connstr_logsqueue
#        - name: AZURE_SB_CONN_STR
#          valueFrom:
#            secretKeyRef:
#              name: workload-id-kvmmglogs  
#              key: AzureServiceBusLogsconnstr
        - name: JAVA_OPTIONS
          value: '-Xms2048m -Xmx4096m'
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        ports:
        #- containerPort: 8080
        resources:
          requests:
            memory: "2Gi"
            cpu: "0.5"
          limits:
            memory: "4Gi"
            cpu: "0.7"
#        livenessProbe:
#          httpGet:
#            path: /actuator/health
#            port: 8080
#          initialDelaySeconds: 60
#          periodSeconds: 10
#          failureThreshold: 3
#        readinessProbe:
#          httpGet:
#            path: /actuator/health
#            port: 8080
#          initialDelaySeconds: 30
#          periodSeconds: 5
#          failureThreshold: 1
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvvault-kvmmglogs-msi"

