apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: filesqueuekedascale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fromfilestologs
  minReplicaCount: 2
  maxReplicaCount: 30
  fallback:
    failureThreshold: 3
    replicas: 2
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 30
          policies:
          - type: Percent
            value: 20
            periodSeconds: 10
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: sbqueuefiles
      namespace: sbmmglogs
      connectionFromEnv: AZURE_SB_CONN_STR
      messageCount: "5" # Optional. Count of messages to trigger scaling on. Default: 5 messages
      activationMessageCount: "2"
      cloud: Private # Optional. Default: AzurePublicCloud
      endpointSuffix: sbmmglogs.servicebus.windows.net # Required when cloud=Private
    #authenticationRef:
    #  name: sbqueuekedascale-trigger-auth