#trigger:
#  branches:
#    include:
#    - master

trigger:
  branches:
    exclude:
    - '*'

variables:
  azsubscriptionConn: 'sc-dowdtf'

pool:
  name: Default
  #demands:
  #- msbuild
  #- visualstudio
  #- vstest

stages:
- stage: Build
  displayName: Preparing manifest file for AKS cluster deployment
  jobs:
  - job: YamlFiles
    steps:
    - checkout: self
      persistCredentials: true
    - task: CopyFiles@2
      displayName: 'Copy manifests'
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)/AKS Resources/manifests'
        contents: '*'
        targetFolder: '$(Build.ArtifactStagingDirectory)'

    - publish: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Publish manifests'
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
#  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'default'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: KubernetesManifest@1
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: '$(azsubscriptionConn)'
              azureResourceGroup: 'rg-spoke-kedaDemo'
              kubernetesCluster: 'aks-keda-demo'
              namespace: 'default'
              manifests: '$(Pipeline.Workspace)/drop/*'
